version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "npm dependencies"
      - "security"
    commit-message:
      prefix: "npm"
      include: "scope" 